// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfqdkyhdgqibtduztphz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmcWRreWhkZ3FpYnRkdXp0cGh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MzQwMDMsImV4cCI6MjA2OTIxMDAwM30.0RYuYjrly-1g7pRacZXLB_msMaSaVDjpUZ2OCh86P7s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});